gem 'sinatra', :require => 'sinatra/base'
gem 'sinatra-content-for2', :require => 'sinatra/content_for2'
gem 'sinatra-static-assets', :require => 'sinatra/static_assets', :git => 'http://github.com/tpeden/sinatra-static-assets.git'
gem 'compass'
gem 'json'
gem 'haml'
